#! /usr/bin/env python2

from linux_modules import depmod
from argparse import ArgumentParser

params = ArgumentParser()
params.add_argument("version")
params.add_argument("-b", "--basedir", default="/")
args = params.parse_args()
depmod(args.basedir, args.version)
